import type { Metadata } from "next";
import { Geist } from "next/font/google";

import { cn } from "@/lib/utils";

import ThemeProvider from "@/components/providers/ThemeProvider";

import "./globals.css";

const geist = Geist({
    subsets: ["latin"],
    variable: "--font-sans",
});

export const metadata: Metadata = {
    title: "Brain Freeze AI",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode;}>) {
  return (
    <html
        lang="en"
        suppressHydrationWarning
        className={cn("font-sans", geist.variable)}
    >
        <body className="min-h-screen">
            <ThemeProvider>
              {children}
            </ThemeProvider>
        </body>
    </html>
  );
}